#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi


# Generate policies
/usr/local/sbin/fwc_policy > /etc/firewall/generated/policies.sh

# Generate zones
/usr/local/sbin/fwc_zone > /etc/firewall/generated/zones.sh

